name = "mintsite-full-production-bundle"
main = "worker/_worker.js"
compatibility_date = "2024-12-01"

[vars]
CF_PROJECT_NAME = "mintsite-full-production-bundle"
RENDER_MODE = "react"

[assets]
directory = "./dist"

kv_namespaces = [
  { binding = "ACTION_E_LOG", id = "2a60ad97002542bbb6b06480ed21c770" },
  { binding = "SESSION_STORE", id = "daf67e9652774ee9b3992924f46d9c7e" }
]

[dev]
kv_namespaces = [
  { binding = "ACTION_E_LOG", id = "2a60ad97002542bbb6b06480ed21c770" },
  { binding = "SESSION_STORE", id = "daf67e9652774ee9b3992924f46d9c7e" }
]

[env.production]
kv_namespaces = [
  { binding = "ACTION_E_LOG", id = "2a60ad97002542bbb6b06480ed21c770" },
  { binding = "SESSION_STORE", id = "daf67e9652774ee9b3992924f46d9c7e" }
]
